### ISSUE TITLE
Scroll HTML issues

### ISSUE THREAD

**Issue by abrudz** [aplteam/Meddy#11]
The Scroll HTML command (F6) seems to jump to the *next* heading. However, if I'm working on some body text, I probably want to see the current section, i.e. the one following the *previous* heading. Also, repeatedly pressing F6 keeps jumping to the next section, which is strange, imho.

I'd also like an option to keep the HTML pane scrolled to the right section instead of manually pressing F6.

**Comment by aplteam** [comment]
The menu command is a misnomer.

I consider to introduce two commands:

* Scroll the previous header - F6
* Scroll to next header - F7

Would that help?

For technical reasons I cannot sync the Markdown with HTML, sorry. The COM object gives me very little to work on. I can jump to what's a bookmark anyway, hence headers.

**Comment by abrudz** [comment]
At least it would make it clear that it isn't broken.

**Comment by abrudz** [comment]
Would it be possible to insert a temporary bookmark at the cursor or at the first visible line, render HTML including moving to that bookmark, remove the bookmark?

**Comment by aplteam** [comment]
Yes, that would be possible: by passing a cursor position with the parameters MarkAPL could inject such a bookmark.

We just need a sponsor for that...
